url: "http://romasharma.com"
pygments: true
exclude: [bin, Gemfile, Gemfile.lock]
markdown: kramdown
permalink: pretty
paginate: 10
#lsi: true

navigations:
- Book Reviews
- Photography
- Travel
- Festivals
- Life's like that
- Baby Food Recipes
- Desserts
kramdown:
  entity_output: symbolic
